### ISSUE TITLE
Energy mix: adjust color styling of diagram

### ISSUE THREAD

**Issue by Nastassia-lk** [innoTUgrid/frontend#71]
**SUMMARY:**
Apply the global theme colors locally within the energy mix diagram. 

**TO-CONSIDER:**

- [x] Use globally defined colors.

**TASKS:**

- [x] Inject globally defined colors in local ts file;
- [x] Areas should be filled with corresponding colors;
- [x] Define Markers object. Markers should be filled with corresponding color;
- [x] Legend should be filled with corresponding color.
