### ISSUE TITLE
Consumption diagram: inject global theme

### ISSUE THREAD

**Issue by Nastassia-lk** [innoTUgrid/frontend#73]
**SUMMARY:**
Apply the global theme colors locally within the consumption diagram.

**TO-CONSIDER:**

- [x] Use globally defined colors;
- [x] Colors should correspond to the associated energy source color solar --> yellow, wind --> blue)

**TASKS:**

- [x]  Inject globally defined colors in local ts file;
- [x]  Areas should be filled with corresponding colors;
- [x]  Define Markers object. Markers should be filled with corresponding color;
- [x]  Legend should be filled with corresponding color.
